### ISSUE TITLE
Name of the API category can be edited using the REST API

### ISSUE THREAD

**Issue by thisaltennakoon** [wso2/apk#1151]
**Description:**
Even though updating the name of the existing API category is not allowed in the Admin UI, it can be updated using [REST API](https://github.com/wso2/apk/blob/main/admin/admin-domain-service/ballerina/resources/admin-api.yaml#L1354)

**Steps to reproduce:**
1. Create an API Category using https://github.com/wso2/apk/blob/main/admin/admin-domain-service/ballerina/resources/admin-api.yaml#L1317
2. Update the name of the API category using https://github.com/wso2/apk/blob/main/admin/admin-domain-service/ballerina/resources/admin-api.yaml#L1354

**Comment by CrowleyRajapakse** [comment]
It's expected behaviour as I remember, Can you verify the behaviour with APIM as well? https://apim.docs.wso2.com/en/latest/reference/product-apis/admin-apis/admin-v4/admin-v4/#tag/API-Category-(Individual)/paths/~1api-categories~1%7BapiCategoryId%7D/put

If it's expected you might need to enable it from UI as well

**Comment by CrowleyRajapakse** [comment]
seems, like this is not the APIM behaviour, need to fix, I checked in APIM
