### ISSUE TITLE
All resources for a single API should be in a single namespace without cross references

### ISSUE THREAD

**Issue by Amila-Rukshan** [wso2/apk#559]
**Description:**
Validations should be added for this scenario until [ReferenceGrant](https://gateway-api.sigs.k8s.io/api-types/referencegrant/?h=referencehttps://gateway-api.sigs.k8s.io/api-types/referencegrant/?h=reference) resource is implemented.

**Comment by AmaliMatharaarachchi** [comment]
Adapter should allow deploying APIs from multiple namespaces. However, configurations of one API i.e. referenced CRs should be contained in one namespace. This restriction is added considering the following reasons;
- Avoid complexity in reference resolving.
- Minimize bugs due to namespace conflicts and reduce the difficulty in debugging issues.

**Comment by AmaliMatharaarachchi** [comment]
this is done
